version: 2.1
orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      #...
      - cypress/run:
          name: Run in Chrome
          requires:
            - cypress/install
          yarn: true
          parallel: true # split all specs across machines
          parallelism: 4 # use 2 CircleCI machines to finish quickly
          executor: cypress/browsers-chrome78-ff70
          browser: chrome
          post-steps:
            - store_artifacts:
                path: cypress/screenshots
            - store_artifacts:
                path: cypress/videos
      #...
      - cypress/run:
          name: Run in Electron
          requires:
            - cypress/install
          yarn: true
          parallel: true # split all specs across machines
          parallelism: 4 # use 2 CircleCI machines to finish quickly
          executor: cypress/browsers-chrome78-ff70
          browser: electron
          post-steps:
            - store_artifacts:
                path: cypress/screenshots
            - store_artifacts:
                path: cypress/videos